import type { Meta, StoryObj } from '@storybook/nextjs-vite'
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion'
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from '@/components/ui/carousel'
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible'
import { Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem, CommandSeparator, CommandShortcut } from '@/components/ui/command'
import { FeatureDialog, FeatureDialogTrigger, FeatureDialogContent, FeatureDialogHeader, FeatureDialogTitle, FeatureDialogDescription, FeatureDialogBody, FeatureDialogFooter } from '@/components/ui/feature-dialog'
import { HoverCard, HoverCardTrigger, HoverCardContent } from '@/components/ui/hover-card'
import { InputGroup, InputGroupAddon, InputGroupInput, InputGroupText, InputGroupButton, InputGroupTextarea } from '@/components/ui/input-group'
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from '@/components/ui/resizable'
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem, SelectGroup, SelectLabel } from '@/components/ui/select'
import { Button } from '@/components/ui/button'

const meta = { title: 'UI/Extended Primitives', parameters: { layout: 'centered' }, decorators: [(Story) => <div className="w-[min(680px,calc(100vw-48px))] space-y-6 p-4"><Story /></div>] } satisfies Meta
export default meta
type Story = StoryObj<typeof meta>
export const Accordions: Story = { render: () => <Accordion defaultValue={['runtime']}><AccordionItem value="runtime"><AccordionTrigger>本地运行时</AccordionTrigger><AccordionContent>数据留在项目隔离环境内。</AccordionContent></AccordionItem><AccordionItem value="models"><AccordionTrigger>模型配置</AccordionTrigger><AccordionContent>通过设置管理模型。</AccordionContent></AccordionItem><AccordionItem value="disabled" disabled><AccordionTrigger>不可用项目</AccordionTrigger><AccordionContent>禁用内容</AccordionContent></AccordionItem></Accordion> }
export const Collapse: Story = { render: () => <Collapsible><CollapsibleTrigger render={<Button variant="outline" />}>显示运行详情</CollapsibleTrigger><CollapsibleContent className="p-4">阶段：已完成 · 耗时：2 秒</CollapsibleContent></Collapsible> }
export const Slides: Story = { render: () => <Carousel className="mx-10"><CarouselContent>{['预览', '代码', '浏览器'].map(label => <CarouselItem key={label}><div className="grid h-48 place-items-center rounded-xl border">{label}</div></CarouselItem>)}</CarouselContent><CarouselPrevious /><CarouselNext /></Carousel> }
export const SearchCommand: Story = { render: () => <Command className="rounded-xl border"><CommandInput placeholder="搜索操作…" /><CommandList><CommandEmpty>没有匹配结果</CommandEmpty><CommandGroup heading="导航"><CommandItem>首页<CommandShortcut>⌘H</CommandShortcut></CommandItem><CommandItem>项目</CommandItem><CommandItem disabled>暂不可用</CommandItem></CommandGroup><CommandSeparator /><CommandGroup heading="设置"><CommandItem>模型与技能</CommandItem></CommandGroup></CommandList></Command> }
export const FeatureModal: Story = { render: () => <FeatureDialog><FeatureDialogTrigger render={<Button />}>新功能</FeatureDialogTrigger><FeatureDialogContent><FeatureDialogHeader><FeatureDialogTitle>项目预览</FeatureDialogTitle><FeatureDialogDescription>查看组件变更。</FeatureDialogDescription></FeatureDialogHeader><FeatureDialogBody>这里使用真实的 FeatureDialog 组合组件。</FeatureDialogBody><FeatureDialogFooter>按 Escape 关闭</FeatureDialogFooter></FeatureDialogContent></FeatureDialog> }
export const HoverPreview: Story = { render: () => <HoverCard><HoverCardTrigger render={<a href="#preview" />}>悬停查看项目</HoverCardTrigger><HoverCardContent>OpenLink · 本地 Agent 工作区</HoverCardContent></HoverCard> }
export const InputGroups: Story = { render: () => <><InputGroup><InputGroupAddon><InputGroupText>https://</InputGroupText></InputGroupAddon><InputGroupInput aria-label="网站地址" placeholder="example.test" /><InputGroupAddon align="inline-end"><InputGroupButton>打开</InputGroupButton></InputGroupAddon></InputGroup><InputGroup><InputGroupTextarea aria-label="提示词" placeholder="输入任务…" /><InputGroupAddon align="block-end"><InputGroupText>0 / 2000</InputGroupText></InputGroupAddon></InputGroup><InputGroup><InputGroupInput disabled aria-label="禁用输入" placeholder="不可用" /></InputGroup><InputGroup><InputGroupInput aria-invalid aria-label="错误输入" defaultValue="无效地址" /></InputGroup></> }
export const SplitPanels: Story = { render: () => <ResizablePanelGroup orientation="horizontal" className="h-64 rounded-lg border"><ResizablePanel defaultSize={35} minSize={20}><div className="p-4">聊天</div></ResizablePanel><ResizableHandle withHandle /><ResizablePanel defaultSize={65} minSize={20}><div className="p-4">预览：拖动中间分隔线</div></ResizablePanel></ResizablePanelGroup> }
export const Scrolling: Story = { render: () => <ScrollArea className="h-64 rounded-lg border"><div className="w-[900px] p-4">{Array.from({ length: 30 }, (_, i) => <p className="py-2" key={i}>文件 {i + 1} · components/workspace/example-{i}.tsx</p>)}</div><ScrollBar orientation="horizontal" /></ScrollArea> }
export const SelectStates: Story = { render: () => <><Select defaultValue="local"><SelectTrigger aria-label="运行环境"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectLabel>运行位置</SelectLabel><SelectItem value="local">Local</SelectItem><SelectItem value="cloud">Cloud</SelectItem><SelectItem value="disabled" disabled>不可用</SelectItem></SelectGroup></SelectContent></Select><Select disabled><SelectTrigger aria-label="禁用选择器"><SelectValue placeholder="不可选择" /></SelectTrigger></Select></> }
